version: '3.8'

services:
  adminer:
    build: 
      context: ./adminer
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  
  postgres:
    build: 
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    env_file:
      - ./.sql_server.conf