version: '3.8'

services:
  adminer:
    image: adminer
    ports:
      - 8080:8080
  
  postgres:
    image: postgres:latest
    build: 
      context: ./db
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    
