@startuml
skinparam componentStyle rectangle

cloud "Docker" {

    package "Python" {
        node "FastAPI" {
            [Python API]
            [Swagger]
        }
    }

    package "Node" as ui_container {
        node "Next.js" as nextjs {
            [Dashboard] as UI
            [Rechart]
        }
    }

    package "Postgres" as postgres_docker {
        database "Postgres" as postgres_db {
            [ACH Tables]
        }
    }
    
note as n1
Folder names of Node, Python, Postgres, etc are the
base images used by the containers
end note

}

[user] --> [UI] : Interfaces with ACH Dashboard
[UI] -> [Rechart] : Visualize Data
[Python API] -> [ACH Tables]: Query
[UI] --> [Python API]: Interface
[Swagger] --> [Python API]: Document



@enduml