@startuml
skinparam monochrome true
skinparam componentStyle rectangle

[<b>Creating a unit test</b>\nListing 5.17\nListing 5.19] as A
[<b>Updating the API</b>\nListing 5.20] as B
[<b>Updating the database</b>\nListing 5.21] as C
[<b>Refactoring code</b>\nListing 5.22\nListing 5.23] as D
[<b>Finishing the unit tests</b>\nListing 5.24] as E

A -> B
B -> C
C -> D
D -> E

@enduml