version: '3.8'

services:
  adminer:
    image: adminer
    ports:
      - 8080:8080
  
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
