@startuml
skinparam monochrome true
skinparam componentStyle rectangle

[<b>Create database table</b>\nListing 6.3] as A
[<b>Testing connectivity</b>\nListing 6.4\nListing 6.5] as B
[<b>Updating the parse routine</b>\nListing 6.6] as C
[<b>Testing with pytest</b>\nListing 6.7\nListing 6.8] as D

A -> B
B -> C
C -> D

@enduml