services:
  cloudbeaver:
    image: cloudbeaver:latest
    ports:
      - 8082:8978
  
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
