version: '3.8'

services:

  cloudbeaver:
    build: 
      context: ./cloudbeaver
      dockerfile: Dockerfile
    ports:
      - 8082:8978     

  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ./.sql_server.conf

  dashboard:
    build: 
      context: ./dashboard
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:8081/api/v1
    ports:
      - 4000:3000

  wiremock:
    build:
      context: ./wiremock
      dockerfile: Dockerfile
    volumes:
      - ./wiremock/__files:/home/wiremock/__files
      - ./wiremock/mappings:/home/wiremock/mappings      
    ports:
      - 8081:8080
      
  postgres:
    build: 
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    env_file:
      - ./.sql_server.conf