@startgantt
saturday are closed
sunday are closed

header ACH Dashboard Enhancements - Round 3

Project starts 2024-08-28

-- Database Design --
[Company Database Design] starts 2024-08-15 and lasts 2 days
[Company API Design] starts at [Company Database Design]'s end and lasts 2 days

-- Company Information Component --
[Company Information UI] starts at [Company Database Design]'s end and lasts 3 days
[Company Information Update Form] starts at [Company Information UI]'s end and lasts 4 days

-- Company Expected Files --
[Expected Files Database Design] starts at [Company Database Design]'s end and lasts 1 day
[Expected Files UI] starts at [Expected Files Database Design]'s end and lasts 2 days

-- Company Recent Batches Component --
[Recent Batches Backend] starts at [Company Database Design]'s end and lasts 3 days
[Expected Files UI] starts at [Expected Files Database Design]'s end and lasts 3 days

-- Company Limit Component --
[Company Limit Backend] starts at [Company Database Design]'s end and lasts 5 days
[Company Limit UI] starts at [Company Limit Backend]'s end and lasts 3 days

[Sprint Complete] happens at 2024-09-11

@endgantt
