@startuml
skinparam monochrome true
skinparam componentStyle rectangle

[<b>Create database table</b>\nListing 6.14] as A
[<b>Code for working with exceptions</b>\nListing 6.15\nListing 6.16] as B
[<b>Code for clearing the database</b>\nListing 6.17] as C

A -> B
B -> C

@enduml