@startgantt
saturday are closed
sunday are closed

header ACH Dashboard Enhancements - Round 3

Project starts 2024-08-28
-- Company Information Enhancement --
[Company Database Design] starts 2024-08-15 and lasts 2 days
[UI Design/Changes] starts at [Company Database Design]'s end and lasts 4 days

-- Company Limit Enhancement --
[UI Changes] starts at 2024-08-15 and lasts 2 days
[ACH Parser Changes] starts at [UI Changes]'s end and lasts 5 days

-- 3rd Party API --
[Implement 3rd Party Alerts] starts at [ACH Parser Changes]'s end and lasts 4 days

-- Regulatory Changes --
[FDIC Logo] starts at 2024-08-15 and lasts 1 day
[PAYROLL Batches] starts at [FDIC Logo]'s end and lasts 3 days

[Sprint Complete] happens at 2024-09-11

@endgantt
