@startuml

while (More ACH exceptions?) 
   :<b>Step 1:</b> Create ACH file with exception condition;
   :<b>Step 2:</b> Update ACH processor to handle exception condition;
   :<b>Step 3:</b> Update Dashboard to present exception condition;
endwhile
-[hidden]->

@enduml
