services:
  cloudbeaver:
    build: 
      context: cloudbeaver
      dockerfile: Dockerfile
    ports:
      - 8082:8978
  
  postgres:
    build: 
      context: ./db
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
  
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - postgres

  web:
    build: 
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 3000:80
    depends_on:
      - api
    
