services:
  cloudbeaver:
    build:
      context: cloudbeaver
      dockerfile: Dockerfile
    ports:
      - 8082:8978
  
  postgres:
    build: 
      context: ./db
      dockerfile: Dockerfile
    env_file:
      - ./.sql_server.conf
  
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - ./.sql_server.conf    
    ports:
      - 8000:8000
    depends_on:
      - postgres

  web:
    build: 
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 3000:80
    depends_on:
      - api
    
