services:

  cloudbeaver:
    build: 
      context: cloudbeaver
      dockerfile: Dockerfile
    ports:
      - 8082:8978
      
  postgres:
    build: 
      context: db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    env_file:
      - .sql_server.conf