services:
  cloudbeaver:
    image: cloudbeaver:latest
    ports:
      - 8082:8978
  
  postgres:
    image: postgres:latest
    build: 
      context: db
      dockerfile: db/Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
  
  api:
    build: 
      context: api
      dockerfile: api/Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - postgres
    
