@startgantt
saturday are closed
sunday are closed

header ACH Dashboard Enhancements - Round 2

Project starts 2024-08-15
-- Searching Enhancement --
[Search API Design] starts 2024-08-15 and lasts 2 days
[UI Design/Changes] starts at \
      [Search API Design]'s end and lasts 4 day

-- Auditing Enhancement --
[Database Design] starts at 2024-08-15 and lasts 2 days
[Review APIs] starts at [Database Design]'s end and lasts 1 days
[Add Auditing logic] starts at [Review APIs]'s end and lasts 3 days
[UI Support for Auditing] starts at [Add Auditing logic]'s end and lasts 3 days

-- Prometheus Monitoring --
[Prometheus Docker Setup] starts at 2024-08-15 and lasts 3 days
[Prometheus Integration] starts at [Prometheus Docker Setup]'s end and lasts 3 days

[Sprint Complete] happens at 2024-08-28

@endgantt
