version: '3.8'

services:
  cloudbeaver:
    image: cloudbeaver:latest
    ports:
      - 8082:8978
  
  postgres:
    image: postgres:latest
    build: 
      context: db
      dockerfile: db/Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    
